DELETE http://localhost:3003/api/blogs/69397169ca1a95d476503e2c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2OTM4OTRmZmNkNzRlY2UxNTA3MzRjNDMiLCJpYXQiOjE3Njg1ODcwNTB9.3C9Oe234wxMeKdXUr2GXOlJepCDIuHnBWPwhOR-jmsQ
# Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIyIiwiaWQiOiI2OTM4OTRmZmNkNzRlY2UxNTA3MzRjNDUiLCJpYXQiOjE3NjUzNzI1NDZ9.IMtu1IkaflgSAFFM2IxuAPZHWKkGRe6aACQkCwKyUXw


### 
GET http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2OTM4OTRmZmNkNzRlY2UxNTA3MzRjNDMiLCJpYXQiOjE3Njg1ODcwNTB9.3C9Oe234wxMeKdXUr2GXOlJepCDIuHnBWPwhOR-jmsQ

###
POST http://localhost:3003/api/blogs
Content-Type: application/json

{
  "title": "My fourth blog",
  "author": "Author 4",
  "url": "http://bloglist.com/my-fourth-blog",
  "likes": 10
}

###
POST http://localhost:3003/api/blogs
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2OTM4OTRmZmNkNzRlY2UxNTA3MzRjNDMiLCJpYXQiOjE3NjUzNTM3Njl9.C4pVB90WnBk5E7RCGXzZPKbNWWjUMn1oiplA4OSy9BQ

{
  "title": "Another blog with authentication",
  "url": "http://bloglist.com/my-fourth-blog",
  "likes": 77
}

###
POST http://localhost:3003/api/blogs/69392bc1fe07591438e4e485/comments
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVzZXIxIiwiaWQiOiI2OTM4OTRmZmNkNzRlY2UxNTA3MzRjNDMiLCJpYXQiOjE3Njg5NzcwMTh9.yPmOhb3_96V_bvRnxJ0ovX9fdt35vmQPJuXP1rNQZno

{
  "comment": "Good post!"
}

###
PUT http://localhost:3003/api/blogs/693066bc1b871b56fe5d7873
Content-Type: application/json

{
  "likes": 24
}